import { Link } from 'wouter';
import { ArrowRight, BookOpen, Brain, Check, Play, TrendingDown, Zap } from 'lucide-react';
import { Metric } from '@/components/Metric';
import { subjects, topics } from '@/data';
import type { ReviewCard, Difficulty } from '@/types';

export function Dashboard({ cards, onGrade }: { cards: ReviewCard[]; onGrade: (id: string, difficulty: Difficulty) => void }) {
  const dueCards = cards.filter((card) => card.due === 'Hoje');
  return <div className="space-y-5">
    <section className="k-grid relative overflow-hidden border border-[#29313d] bg-[#131821] p-5 md:p-7">
      <div className="relative z-10 grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><div className="mb-4 flex items-center gap-2"><span className="k-chip k-chip-active">CICLO 04</span><span className="k-chip">diagnóstico atualizado há 18 min</span></div><h2 className="max-w-[590px] text-[29px] font-semibold leading-[1.02] tracking-[-0.055em] md:text-[39px]">O que move sua nota agora é <span className="k-focus">Matemática.</span></h2><p className="mt-4 max-w-[520px] text-[13px] leading-6 text-[#aeb8c5]">Porcentagem e Lei de Acesso à Informação concentram os maiores riscos. Resolva uma sessão curta antes de abrir conteúdo novo.</p><div className="mt-6 flex flex-wrap gap-2"><Link href="/questoes" className="k-button k-button-primary" data-testid="link-start-next-action"><Play size={14} fill="currentColor" /> Começar sessão recomendada</Link><Link href="/estudo" className="k-button" data-testid="link-open-study"><BookOpen size={14} /> Abrir estudo</Link></div></div><div className="flex flex-col justify-between border-l border-[#29313d] pl-6 lg:min-h-[178px]"><p className="k-eyebrow">até a prova</p><div><p className="k-mono text-[60px] leading-none tracking-[-0.08em] text-[#d5f35b]">42</p><p className="mt-2 text-[12px] text-[#aeb8c5]">dias restantes · 17 janeiro 2026</p></div><div className="flex gap-6 text-[11px]"><span><strong className="k-mono text-[#f0f0e8]">14</strong><span className="ml-1 text-[#8e98a8]">sessões planejadas</span></span><span><strong className="k-mono text-[#f0f0e8]">3</strong><span className="ml-1 text-[#8e98a8]">revisões vencidas</span></span></div></div></div>
    </section>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="progresso geral" value="47,2%" note="+6,8 p.p. em 14 dias" accent /><Metric label="questões resolvidas" value="84" note="64 corretas · 20 incorretas" /><Metric label="retenção média" value="68%" note="últimas 32 revisões" /><Metric label="tempo de foco" value="6h 20" note="esta semana · meta 8h" /></div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <section className="k-card p-5"><div className="mb-5 flex items-center justify-between"><div><p className="k-eyebrow">cobertura por matéria</p><h3 className="mt-1 text-[16px] font-semibold">Onde seu tempo está rendendo</h3></div><Link href="/edital" className="k-button k-button-quiet text-[11px]" data-testid="link-view-syllabus">Ver edital <ArrowRight size={13} /></Link></div><div className="space-y-5">{subjects.map((subject) => <div key={subject.id} data-testid={`row-subject-${subject.id}`}><div className="mb-2 flex items-center justify-between text-[12px]"><span className="flex items-center gap-2 font-medium"><span className="h-2 w-2 rounded-full" style={{ background: subject.color }} />{subject.name}</span><span className="k-mono text-[#aeb8c5]">{subject.progress}% <span className="text-[#657181]">/ peso {subject.weight}%</span></span></div><div className="k-progress"><span style={{ width: `${subject.progress}%`, background: subject.color }} /></div><div className="mt-2 flex justify-between text-[10px] text-[#6f7b8b]"><span>{subject.questions} questões no diagnóstico</span><span>{subject.progress < 50 ? 'abaixo do corte' : 'ritmo consistente'}</span></div></div>)}</div></section>
      <section className="k-card p-5"><div className="mb-5 flex items-center justify-between"><div><p className="k-eyebrow">próximas revisões</p><h3 className="mt-1 text-[16px] font-semibold">Fila de hoje</h3></div><Link href="/revisao" className="k-button k-button-quiet text-[11px]" data-testid="link-view-reviews">Abrir fila <ArrowRight size={13} /></Link></div><div className="space-y-2">{dueCards.map((card) => <div key={card.id} className="flex items-center gap-3 border-t border-[#242c37] py-3"><span className={`h-2 w-2 rounded-full ${card.difficulty === 'difícil' ? 'bg-[#ff907d]' : 'bg-[#d5f35b]'}`} /><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-medium">{card.topic}</p><p className="mt-1 text-[10px] text-[#8e98a8]">{card.difficulty} · vencimento {card.due.toLowerCase()}</p></div><button className="k-button k-button-quiet k-icon-button" onClick={() => onGrade(card.id, 'bom')} data-testid={`button-quick-review-${card.id}`} aria-label={`Marcar ${card.topic} como bom`}><Check size={15} /></button></div>)}</div><div className="mt-4 border border-dashed border-[#394452] p-3 text-[11px] text-[#8e98a8]"><span className="k-focus">Fila leve.</span> Complete as 3 cartas para liberar o próximo bloco.</div></section>
    </div>
    <div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><section className="k-card p-5"><div className="mb-5 flex items-center gap-2"><TrendingDown size={16} className="k-coral" /><div><p className="k-eyebrow">pontos de atenção</p><h3 className="mt-1 text-[16px] font-semibold">Onde você está perdendo pontos</h3></div></div><div className="space-y-3">{topics.filter((topic) => topic.priority === 'alta').map((topic) => <Link href="/estudo" key={topic.id} className="flex items-center gap-3 border-t border-[#242c37] py-3" data-testid={`link-weak-topic-${topic.id}`}><span className="k-mono w-9 text-[11px] text-[#ff907d]">{topic.accuracy}%</span><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-medium">{topic.name}</p><p className="mt-1 text-[10px] text-[#8e98a8]">{topic.subject} · {topic.lastStudied}</p></div><ArrowRight size={14} className="text-[#68788b]" /></Link>)}</div></section><section className="k-card-soft p-5"><div className="flex items-start gap-4"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-sm bg-[#283322] text-[#d5f35b]"><Zap size={17} /></div><div><p className="k-eyebrow">próximo movimento</p><h3 className="mt-1 text-[17px] font-semibold">Resolver 8 questões de porcentagem</h3><p className="mt-2 max-w-[510px] text-[12px] leading-5 text-[#aeb8c5]">Sessão calibrada para 25 minutos. A meta é identificar se o erro é de fórmula, leitura ou operação — não apenas acumular acertos.</p><div className="mt-5 flex flex-wrap items-center gap-3"><Link href="/questoes" className="k-button k-button-primary" data-testid="link-recommended-session"><Play size={14} fill="currentColor" /> Iniciar agora</Link><span className="k-mono text-[10px] text-[#7e8998]">8 itens · 25 min · nível misto</span></div></div></div></section></div>
  </div>;
}
